### PR TITLE
No timeout & max request limits

### PR DESCRIPTION
**Pull request by benoit-canet**
PR to review and test with care before merging since the no timeout test is intrusive

### CODE REVIEW

**Comment by lmr** [comment]
Overall, this looks good. Travis just complained about a minor thing:

    $ inspekt lint
    Pylint disabled: C,E,R,W,F0401,I0011
    Pylint enabled : W0611
    ************* Module queries-limits
    W0611:  3,0: : Unused import boto3
    W0611:  5,0: : Unused import threading
    Pylint check fail: /home/travis/build/scylladb/scylla-longevity-tests/queries-limits.py
    Syntax check FAIL

**Comment by lmr** [comment]
@benoit-canet I can merge the PR as is, then send the little fixes I suggested, or you can fix them and rebase the PR, it's up to you.

**Comment by benoit-canet** [comment]
I will fix them and rebase them.

I also prefer that we put this pr on hold waiting for 0.17 that will make
most of tests pass again.
We cannot apply code we didn't fully tested.

**Comment by benoit-canet** [comment]
Thanks for the review.

**Comment by lmr** [comment]
@benoit-canet that's fine, we can hold until we have a more recent AMI to test this with. I asked @slivne to see if it's possible to have AMI builds straight from scylla master that we can use to test scylla bugfixes, he said he'll look into it.

**Pull request merged**
