### PR TITLE
Nemesis timeline work

### PR DESCRIPTION
**Pull request by lmr**
This PR adds nemesis event visualization in c-s generated graphs.

An example of the end result can be seen on the attached png files:

node lmr-scylla-loader-node-4de108f3-1 54 191 40 40 - 172 31 35 26 seed- none -ops svg
latency

### CODE REVIEW

**Comment by lmr** [comment]
@slivne and @asias, I guess this is a reasonable start.

**Comment by asias** [comment]
@lmr so the blue dot line is the start of the Nemesis and the red dot line is the end of the Nemesis.

**Comment by slivne** [comment]
how do we know which nemesis it was ?

**Comment by slivne** [comment]
to make it clear

the stop/start nemesis will probably have a different effect then the add
node / corrupt and repair nemesis - it would be useful if possible to
provide info as to which nemesis ran in each period

**Comment by lmr** [comment]
@slivne, it's possible, but we had a couple of problems:

1) Labels take way too much space, to the point where they obscure important parts of the graph
2) We'd have to start rolling random colors for each event to tell them apart right there in the graph, which is possible, but then we run into 1) again - how to tell which color belongs to which event of which nemesis.

**Comment by lmr** [comment]
So I think until I learn some new matplotlib trick I don't know of, we can always look at the operation log to tell them apart.

**Comment by slivne** [comment]
Sure

**Pull request merged**
